/*
    @author kimmerrvargas
 */
public class Calculator extends javax.swing.JFrame {

    double firstNum;
    double secondNum;
    double answer;
    String operator;
    public Calculator() {
        setLocation(550, 200);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnC = new javax.swing.JButton();
        jbtnCE = new javax.swing.JButton();
        jbtnDel = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnMultiply = new javax.swing.JButton();
        jbtnNum9 = new javax.swing.JButton();
        jbtnNum8 = new javax.swing.JButton();
        jbtnNum7 = new javax.swing.JButton();
        jbtnMinus = new javax.swing.JButton();
        jbtnNum6 = new javax.swing.JButton();
        jbtnNum5 = new javax.swing.JButton();
        jbtnNum4 = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnNum3 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNum0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnEquals = new javax.swing.JButton();
        jtxtResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(345, 470));
        setSize(new java.awt.Dimension(350, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnC.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 86, 60, 60));

        jbtnCE.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 86, 60, 60));

        jbtnDel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jbtnDel.setText("Del");
        jbtnDel.setActionCommand("");
        jbtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 86, 60, 60));

        jbtnDivide.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnDivide.setText("/");
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 86, 60, 60));

        jbtnMultiply.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnMultiply.setText("*");
        jbtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 152, 60, 60));

        jbtnNum9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum9.setText("9");
        jbtnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum9, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 152, 60, 60));

        jbtnNum8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum8.setText("8");
        jbtnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum8, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 152, 60, 60));

        jbtnNum7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum7.setText("7");
        jbtnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 152, 60, 60));

        jbtnMinus.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnMinus.setText("-");
        jbtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 218, 60, 60));

        jbtnNum6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum6.setText("6");
        jbtnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 218, 60, 60));

        jbtnNum5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum5.setText("5");
        jbtnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 218, 60, 60));

        jbtnNum4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum4.setText("4");
        jbtnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 218, 60, 60));

        jbtnPlus.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 284, 60, 60));

        jbtnNum3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum3.setText("3");
        jbtnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 284, 60, 60));

        jbtnNum2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum2.setText("2");
        jbtnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 284, 60, 60));

        jbtnNum1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum1.setText("1");
        jbtnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 284, 60, 60));

        jbtnNum0.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnNum0.setText("0");
        jbtnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNum0, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 350, 132, 60));

        jbtnDot.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 350, 60, 60));

        jbtnEquals.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnEquals.setText("=");
        jbtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 350, 60, 60));

        jtxtResult.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 19, 276, 49));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void EnterNumbers(String n){
        String numbers = jtxtResult.getText() + n;
        jtxtResult.setText(numbers);
    }
            
    private void jbtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDelActionPerformed
        String del = null;
        if(jtxtResult.getText().length() > 0){
            StringBuilder sb = new StringBuilder(jtxtResult.getText());
            sb.deleteCharAt(jtxtResult.getText().length() - 1);
            del = sb.toString();
            jtxtResult.setText(del);
        }
    }//GEN-LAST:event_jbtnDelActionPerformed

    private void jbtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_jbtnNum7ActionPerformed

    private void jbtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtnNum8ActionPerformed

    private void jbtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_jbtnNum9ActionPerformed

    private void jbtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jbtnNum4ActionPerformed

    private void jbtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jbtnNum5ActionPerformed

    private void jbtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtnNum6ActionPerformed

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jbtnNum1ActionPerformed

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jbtnNum2ActionPerformed

    private void jbtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jbtnNum3ActionPerformed

    private void jbtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jbtnNum0ActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
        firstNum = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        operator = "/";
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiplyActionPerformed
        firstNum = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        operator = "*";
    }//GEN-LAST:event_jbtnMultiplyActionPerformed

    private void jbtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinusActionPerformed
        firstNum = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        operator = "-";
    }//GEN-LAST:event_jbtnMinusActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
        firstNum = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        operator = "+";
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtResult.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtxtResult.setText("");
        String fNum, sNum;
        fNum = String.valueOf(firstNum);
        sNum = String.valueOf(secondNum);
        fNum = "";
        sNum = "";
    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        if(! jtxtResult.getText().contains(".")){
            jtxtResult.setText(jtxtResult.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualsActionPerformed
        secondNum = Double.parseDouble(jtxtResult.getText());
        if(operator == "+"){
            answer = firstNum + secondNum;
            jtxtResult.setText(String.valueOf(answer));
        }
        else if (operator == "-"){
            answer = firstNum - secondNum;
            jtxtResult.setText(String.valueOf(answer));
        }
        else if (operator == "*"){
            answer = firstNum * secondNum;
            jtxtResult.setText(String.valueOf(answer));
        }
        else if (operator == "/"){
            answer = firstNum / secondNum;
            jtxtResult.setText(String.valueOf(answer));
        }
    }//GEN-LAST:event_jbtnEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDel;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEquals;
    private javax.swing.JButton jbtnMinus;
    private javax.swing.JButton jbtnMultiply;
    private javax.swing.JButton jbtnNum0;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnNum3;
    private javax.swing.JButton jbtnNum4;
    private javax.swing.JButton jbtnNum5;
    private javax.swing.JButton jbtnNum6;
    private javax.swing.JButton jbtnNum7;
    private javax.swing.JButton jbtnNum8;
    private javax.swing.JButton jbtnNum9;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
